# Generated by Django 5.2.16 on 2026-08-06 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_create_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizevariant',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
