# Generated by Django 6.1 on 2026-08-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20260813_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
