# Generated by Django 6.0.6 on 2026-08-13 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ban_user', 'You banned a user'), ('unban_user', 'You unbanned a user'), ('approve_deposit', 'You approved a deposit'), ('reject_deposit', 'You rejected a deposit'), ('approve_withdraw', 'You approved a withdrawal'), ('reject_withdraw', 'You rejected a withdrawal'), ('approve_post', 'You approved a post'), ('reject_post', 'You rejected a post')], max_length=50)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
