# Generated by Django 6.0.6 on 2026-08-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactivity',
            name='message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
