# Generated by Django 6.0.6 on 2026-08-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_adminactivity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
