# Generated by Django 6.1 on 2026-08-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_adminactivity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
