"""
Django settings for trustyshop project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = 'django-insecure-z=d@zy6vop!ftw51zjh^kqo&a@u2n6fys6+=9)=)ed_x2k!*-1'

DEBUG = True
ALLOWED_HOSTS = [
 "*"
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'welcome',
    'widget_tweaks',
    'user.apps.UserConfig',
    'posts',
    'adminpanel',
    'notifications',
    'wallet.apps.WalletConfig',
    'wishlist',
    'cart',
    'image_search',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trustyshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'adminpanel.context_processors.admin_notifications',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notification_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'trustyshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ============================================================
# SITE URL
# ============================================================

SITE_URL = "http://172.16.61.162:8000"



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'user.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Yangon'

USE_I18N = True

USE_TZ = True




STATIC_URL = 'static/'




MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ============================================================
# LOGIN / LOGOUT
# ============================================================

LOGIN_URL = '/user/login/'

LOGIN_REDIRECT_URL = 'home'

LOGOUT_REDIRECT_URL = 'login'

# ============================================================
# REMEMBER ME / SESSION
# ============================================================

# Default session expires when the browser is closed.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Used when Remember Me is checked.
SESSION_COOKIE_AGE = 30 * 24 * 60 * 60  # 30 days


ABSTRACT_API_KEY = 'fca5f07a0196476e9826b73ad5b2ed86'


EMAIL_BACKEND = 'trustyshop.email_backend.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587

EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_HOST_USER = 'trustyshop064@gmail.com'

# Paste your 16-character Gmail App Password below
EMAIL_HOST_PASSWORD = 'vwjaldffphkbhoia'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
