# Generated by Django 6.0.7 on 2026-08-04 13:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_withdraw_user_alter_wallet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'), message='Minimum deposit amount is 1,000 MMK.')]),
        ),
        migrations.AlterField(
            model_name='depositrequest',
            name='sender_phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Myanmar phone number (e.g. 09123456789).', regex='^09\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'), message='Minimum withdraw amount is 1,000 MMK.')]),
        ),
    ]
