# Generated by Django 6.0.6 on 2026-08-04 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_remove_withdraw_user_alter_wallet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='sender_phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Myanmar phone number (e.g. 09123456789).', regex='^09\\d{9}$')]),
        ),
    ]
