# Generated by Django 6.0.7 on 2026-08-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_depositrequest_amount_and_more'),
        ('wallet', '0003_alter_depositrequest_sender_phone'),
    ]

    operations = [
    ]
