# Generated by Django 6.0.6 on 2026-08-08 01:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_merge_20260807_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'))]),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'))]),
        ),
        migrations.AlterField(
            model_name='withdrawrequest',
            name='receiver_phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Myanmar phone number (e.g. 09123456789).', regex='^09\\d{9}$')]),
        ),
    ]
