# Generated by Django 6.0.6 on 2026-08-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_depositrequest_amount_and_more'),
        ('wallet', '0005_alter_wallet_options_depositrequest_updated_at_and_more'),
    ]

    operations = [
    ]
