# Generated by Django 6.0.6 on 2026-08-13 12:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('checked_out', 'Checked out'), ('abandoned', 'Abandoned')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('item_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('taken', 'Taken'), ('released', 'Released'), ('purchased', 'Purchased'), ('cancelled', 'Cancelled')], default='taken', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cart.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.item')),
                ('size_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.sizevariant')),
            ],
        ),
        migrations.CreateModel(
            name='StockHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('taken', 'Taken'), ('released', 'Released'), ('purchased', 'Purchased')], default='taken', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='cart.cartitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.item')),
                ('size_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.sizevariant')),
            ],
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['status'], name='cart_cartit_status_401e96_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhold',
            index=models.Index(fields=['status', 'expires_at'], name='cart_stockh_status_4e355d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhold',
            index=models.Index(fields=['item', 'size_variant', 'status'], name='cart_stockh_item_id_3c0784_idx'),
        ),
    ]
