# Generated by Django 5.2.16 on 2026-07-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_phone_number'),
        ('user', '0002_auto_20260720_0129'),
    ]

    operations = [
    ]
