# Generated by Django 5.2.16 on 2026-08-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_terms_accepted_profile_terms_accepted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
