# Generated by Django 5.2.16 on 2026-07-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merge_20260720_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fullName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
