# Generated by Django 6.0.6 on 2026-08-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
