# Generated by Django 6.0.6 on 2026-08-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_post', 'New Post'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deposit_request', 'Deposit Request'), ('deposit_approved', 'Deposit Approved'), ('deposit_rejected', 'Deposit Rejected'), ('withdraw_approved', 'Withdraw Approved'), ('withdraw_rejected', 'Withdraw Rejected'), ('order_created', 'Order Created'), ('order_ready', 'Order Ready'), ('order_picked_up', 'Order Picked Up'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled'), ('payment_released', 'Payment Released'), ('payment_received', 'Payment Received')], max_length=30),
        ),
    ]
