# Generated by Django 6.0.6 on 2026-08-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_post', 'New Post'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deposit_request', 'Deposit Request'), ('deposit_approved', 'Deposit Approved'), ('deposit_rejected', 'Deposit Rejected')], max_length=20),
        ),
    ]
