# Generated by Django 5.2.16 on 2026-08-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_auto_ready_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='auto_ready_at',
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
