# Generated by Django 5.2.16 on 2026-08-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_auto_ready_at_order_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='auto_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
