# Generated by Django 5.2.16 on 2026-08-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_auto_ready_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
